Sync files from swift-dns/shared (#26)
Co-authored-by: swift-dns-helper[bot] <295214583+swift-dns-helper[bot]@users.noreply.github.com>

diff --git a/.github/workflows/nightly-tests.yml b/.github/workflows/nightly-tests.yml
--- a/.github/workflows/nightly-tests.yml
+++ b/.github/workflows/nightly-tests.yml
@@ -10,7 +10,7 @@ on:
 
 defaults:
   run:
-    shell: bash --noprofile --norc -e -u -o pipefail {0}
+    shell: bash --noprofile --norc -Eeuo pipefail {0}
 
 jobs:
   linux-nightly-tests:
@@ -70,6 +70,7 @@ jobs:
         run: |
           # keeping code coverage flag to check for regressions
           swift test \
+            --skip "IntegrationTests." \
             --skip-build \
             --enable-code-coverage \
             -Xswiftc -require-explicit-sendable \
@@ -269,6 +270,7 @@ jobs:
         run: |
           # keeping code coverage flag to check for regressions
           swift test \
+            --skip "IntegrationTests." \
             --skip-build \
             --enable-code-coverage \
             -Xswiftc -require-explicit-sendable \
@@ -289,24 +291,22 @@ jobs:
     timeout-minutes: 30
 
     steps:
-      - name: Free disk space for emulator
-        run: |
-          sudo rm -rf /opt/microsoft /opt/google /opt/az /usr/share/miniconda /usr/share/az* /usr/share/glade* /usr/local/share/chromium /usr/local/share/powershell /usr/share/dotnet /opt/ghc /opt/hostedtoolcache/CodeQL /usr/local/share/boost
-          docker image prune --all --force
-          docker builder prune -a
-
       - name: Ensure zstd is available for faster caching
         run: sudo apt-get update -yq && sudo apt-get install -yq zstd
 
       - name: Check out code
         uses: actions/checkout@v7
+        with:
+          persist-credentials: false
 
       - name: Replace symlinks with the actual files
         run: find . -type l -exec sh -c 'LINKED="$(readlink -f "{}")"; rm "{}"; cp -a "$LINKED" "{}"' \;
 
       - name: Run unit tests
-        uses: skiptools/swift-android-action@v2
+        uses: skiptools/swift-android-action@2044b79660f201ccef8cbce62877e4ec5409f9c8 # v2.9.5
         with:
+          # Ubuntu runners low on space causes the emulator to fail to install
+          free-disk-space: true
           android-emulator-test-folder: /data/local/tmp/android-xctest
           test-env: PROJECT_ROOT_FOR_TESTING=/data/local/tmp/android-xctest
           swift-version: ${{ matrix.swift.version }}
